#!/usr/bin/env bash

source config

if [ ! -z ${DOCKER_ID} ]; then
    docker stop ${DOCKER_ID}
    docker rm ${DOCKER_ID} --force
else
    echo -e "Docker Image ID not detected. Check docker image list:\n"
    docker images
fi